# genome reference that reads were aligned to
reference:
  build: hg19
  fasta: resources/hg19_ion/hg19.fasta


exome:
  # amplicon (amplification) or hybrid (capture) for exome analysis
  method: amplicon
  targets: resources/ampliseq/AmpliSeqExome.20141113.designed.bed


test-samples:
  table: config/test-samples.tsv
  dir: resources/exomes


baseline-samples:
  table: config/baseline-samples.tsv
  dir: resources/exomes


common:
  # whether to split tests considering samples' sex
  match-sex: false
  sample-regex: 'NA[0-9]{5}'


exome-depth:
  # mirror to download R packages from
  # find the CRAN mirror nearest to you to minimize network load on https://cran.r-project.org
  repository: https://cran-r.c3sl.ufpr.br/
